Alter table LIB_FEAT drop constraint LIB_FEAT_PK;
Drop index LIB_FEAT. LIB_FEAT_SK;
ALTER TABLE LIB_FEAT ADD CONSTRAINT LIB_FEAT_PK PRIMARY KEY CLUSTERED (LIB_FEAT_ID) WITH (OPTIMIZE_FOR_SEQUENTIAL_KEY=ON, FILLFACTOR=100);
-- make this PK be clustered
CREATE UNIQUE INDEX LIB_FEAT_SK ON LIB_FEAT(FEAT_HASH, FTYPE_ID, ANONYMIZED)
GO


alter table DSRC_RECORD drop constraint DSRC_RECORD_PK;
Drop index DSRC_RECORD.DSRC_RECORD_SK;
--- UNCHANGED
ALTER TABLE DSRC_RECORD ADD CONSTRAINT DSRC_RECORD_PK PRIMARY KEY NONCLUSTERED (RECORD_ID, DSRC_ID)
CREATE INDEX DSRC_RECORD_SK ON DSRC_RECORD(ENT_SRC_KEY, DSRC_ID)

alter table OBS_ENT drop constraint OBS_ENT_PK;
Drop index OBS_ENT.OBS_ENT_SK;
ALTER TABLE OBS_ENT ADD CONSTRAINT OBS_ENT_PK PRIMARY KEY NONCLUSTERED (OBS_ENT_ID) WITH (OPTIMIZE_FOR_SEQUENTIAL_KEY=ON)
CREATE UNIQUE INDEX OBS_ENT_SK ON OBS_ENT(ENT_SRC_KEY, DSRC_ID)

alter table RES_ENT drop constraint RES_ENT_PK;
ALTER TABLE RES_ENT ADD CONSTRAINT RES_ENT_PK PRIMARY KEY NONCLUSTERED (RES_ENT_ID) WITH (OPTIMIZE_FOR_SEQUENTIAL_KEY=ON)

alter table RES_ENT_OKEY drop constraint RES_ENT_OKEY_PK;
Drop index RES_ENT_OKEY.RES_ENT_OKEY_SK;
ALTER TABLE RES_ENT_OKEY ADD CONSTRAINT RES_ENT_OKEY_PK PRIMARY KEY NONCLUSTERED (OBS_ENT_ID)
CREATE CLUSTERED INDEX RES_ENT_OKEY_SK ON RES_ENT_OKEY(RES_ENT_ID, OBS_ENT_ID)

alter table RES_FEAT_EKEY drop constraint RES_FEAT_EKEY_PK;
Drop index RES_FEAT_EKEY.RES_FEAT_EKEY_SK;
-- make this PK be clustered
ALTER TABLE RES_FEAT_EKEY ADD CONSTRAINT RES_FEAT_EKEY_PK PRIMARY KEY CLUSTERED (RES_ENT_ID, LIB_FEAT_ID, UTYPE_CODE)
 -- already unique based on the PK
CREATE INDEX RES_FEAT_EKEY_SK ON RES_FEAT_EKEY(LIB_FEAT_ID, RES_ENT_ID, UTYPE_CODE)

alter table RES_FEAT_STAT drop constraint RES_FEAT_STAT_PK;
-- make this PK be clustered
ALTER TABLE RES_FEAT_STAT ADD CONSTRAINT RES_FEAT_STAT_PK PRIMARY KEY CLUSTERED (LIB_FEAT_ID) WITH (OPTIMIZE_FOR_SEQUENTIAL_KEY=ON);

alter table RES_RELATE drop constraint RES_RELATE_PK;
ALTER TABLE RES_RELATE ADD CONSTRAINT RES_RELATE_PK PRIMARY KEY NONCLUSTERED (RES_REL_ID) WITH (OPTIMIZE_FOR_SEQUENTIAL_KEY=ON)

alter table RES_REL_EKEY drop constraint RES_REL_EKEY_PK;
-- make this PK be clustered
ALTER TABLE RES_REL_EKEY ADD CONSTRAINT RES_REL_EKEY_PK PRIMARY KEY CLUSTERED (RES_ENT_ID, REL_ENT_ID)

alter table LIB_UTYPE drop constraint LIB_UTYPE_PK;
-- UNCHANGED
ALTER TABLE LIB_UTYPE ADD CONSTRAINT LIB_UTYPE_PK PRIMARY KEY NONCLUSTERED (UTYPE_CODE)
GO
